
import templateCarouselImg from '../Images/Projects/template-w-carousel.png'
import watchProductsImg from '../Images/Projects/watch-products.png'
import basicCalculatorImg from '../Images/Projects/basic-calculator.png'
import currencyExchangeImg from '../Images/Projects/currency-exchange.jpg'
import caraShopingImg from '../Images/Projects/cara-shoping.png'
import lusionShoppingImg from '../Images/Projects/react-lusion-app.jpg'
import simpleMoviesImg from '../Images/Projects/simple-movies.jpg'
import simpleMoviesReduxImg from '../Images/Projects/simple-movies-redux.jpg'


export const startLink = ''


export const myPersonalInfo = [
   {  id:201,
      title:'Frist Name: ',
      info: 'Mustafa' ,
      color: 'var(--mainPraimary)',
   },
   {  id:202,
      title:'Last Name: ',
      info: 'Abutabl' ,
      color: 'var(--mainPraimary)',
   },
   {  id:203,
      title:'Birthdate: ',
      info: '19/10/1989' ,
      color: 'var(--mainPraimary)',
   },
   {  id:204,
      title:'Nationality: ',
      info: 'Egyption' ,
      color: 'var(--mainPraimary)',
   },
   {  id:205,
      title:'Military Service: ',
      info: ' Finshed' ,
      color: 'var(--mainPraimary)',
   },
   {  id:206,
      title:'Langages: ',
      info: 'Arabic, English' ,
      color: 'var(--mainPraimary)',
   },
   {  id:208,
      title:'Phone: ',
      info: '+20 111 970 6667' ,
      color: 'var(--mainPraimary)',
   },
   {  id:207,
      title:'Email: ',
      info: 'eng.mustafa@hotmail.com' ,
      color: 'var(--mainPraimary)',
   },
   {  id:209,
      title:'Freelance: ',
      info: 'Available' ,
      color: '#01ef92',
   },
]





export const myProjects = [
   {  id:108,
      title:'Simple Movies with Redux',
      img: simpleMoviesReduxImg ,
      link:'https://simplemovies-redux.netlify.app',
      Language :['HTML', 'CSS', 'Material Ui', 'Javascript', 'React', 'Redux'],
      description: 'Simple movies website to discover popular movies, and add to favorite list, with using Redux.',
   },
   {  id:107,
      title:'Simple Movies',
      img: simpleMoviesImg ,
      link:'https://simplemovies-app.netlify.app',
      Language :['HTML', 'CSS', 'Material Ui', 'Javascript', 'React'],
      description: 'Simple movies website to discover popular movies, and add to favorite list.',
   },
   {  id:106,
      title:'Lusion Shopping',
      img: lusionShoppingImg ,
      link:'https://react-lusion-app.netlify.app',
      Language :['HTML', 'CSS', 'Bootstrap', 'Javascript', 'React'],
      description: 'Lustion ecommerce web responsive with many pages and form validation.',
   },
   {  id:105,
      title:'Cara Shoping',
      img: caraShopingImg ,
      link:'https://cara-shoping.vercel.app',
      Language :['HTML', 'CSS', 'Bootstrap', 'Javascript'],
      description: 'responsive ecommerce website main page, sign up and sign in made with js.',
   },
   {  id:104,
      title:'Currency Exchange',
      img: currencyExchangeImg ,
      link:'https://currency-exchange-mu.vercel.app',
      Language :['HTML', 'CSS', 'Bootstrap', 'Javascript'],
      description: 'This is a simple Currency Converter application, I took help from this website, "exchangerate-api" to create an API connection.',
   },
   {  id:103,
      title:'Basic Calculator',
      img: basicCalculatorImg ,
      link:'https://basic-calculator-self.vercel.app',
      Language :['HTML', 'CSS', 'Bootstrap', 'Javascript'],
      description: 'Basic Calculator for doing simple mathematical operations: addition, subtraction, multiplication, division. This is a simplified version of the online.',
   },
   {  id:102,
      title:'Watch Products',
      img: watchProductsImg,
      link:'https://watch-products.vercel.app',
      Language :['HTML', 'CSS', 'Bootstrap'],
      description: 'single page responsive website.',
   },
   {  id:101,
      title:'Template W Carousel',
      img: templateCarouselImg,
      link:'https://template-w-carousel.vercel.app',
      Language :['HTML', 'CSS', 'Bootstrap'],
      description: 'single page responsive website.',
   },
]
